/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "var(--on-tertiary)",
        "on-error-container": "var(--on-error-container)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "error-container": "var(--error-container)",
        "inverse-surface": "var(--inverse-surface)",
        "secondary-container": "var(--secondary-container)",
        "surface": "var(--surface)",
        "surface-tint": "var(--surface-tint)",
        "surface-bright": "var(--surface-bright)",
        "on-primary": "var(--on-primary)",
        "primary-fixed": "var(--primary-fixed)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-surface": "var(--on-surface)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-background": "var(--on-background)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "primary-container": "var(--primary-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container-high": "var(--surface-container-high)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "outline": "var(--outline)",
        "on-error": "var(--on-error)",
        "surface-container": "var(--surface-container)",
        "error": "var(--error)",
        "surface-variant": "var(--surface-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-secondary": "var(--on-secondary)",
        "secondary-fixed": "var(--secondary-fixed)",
        "primary": "var(--primary)",
        "tertiary": "var(--tertiary)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "secondary": "var(--secondary)",
        "background": "var(--background)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "tertiary-container": "var(--tertiary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-max": "1280px",
        "margin-desktop": "80px",
        "gutter": "32px",
        "section-gap": "120px",
        "stack-lg": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "display-lg-mobile": ["Cormorant Garamond", "serif"],
        "label-ar": ["Cairo", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "headline-lg": ["Cormorant Garamond", "serif"],
        "display-lg": ["Cormorant Garamond", "serif"],
        "headline-xl": ["Cormorant Garamond", "serif"],
        "cta": ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
